services:
  nginx-1:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks: 
      - my-network
    restart: always
  hping:
    image: dockersec/hping3:latest
    ports:
      - "5001:5001"
    # volumes:
    #   - ./nginx.conf:/etc/nginx/nginx.conf
    networks: 
      - my-network
    restart: always

networks:
  my-network:
    driver: bridge